#!/usr/bin/env python

import sys
from PyQt4 import QtGui
from fungui.app import App 


def main():
    qtapp = QtGui.QApplication(sys.argv)
    app = App()
    app.run()
    sys.exit(qtapp.exec_())

if __name__ == '__main__':
    main()
