#!/usr/bin/env python

import sys
from PyQt4 import QtGui
from fungui.app import MainWindow


def main():
    app = QtGui.QApplication(sys.argv)
    mw = MainWindow()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
